### ISSUE TITLE
Password strength meter option controls the visibility of the password length option, and it shouldn't

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#101]
### Reproduction Steps

+ Add a password block
+ make sure the password strength meter option is turned off

### Expected Behavior

+ I would still expect to be able to customize the min password length

### Actual Behavior

+ I'm not able to customizer the min password length

### Error Messages / Logs

n\a

### System and Environment Information

LifterLMS Blocks with head at https://github.com/gocodebox/lifterlms-blocks/commit/dafd798e416017fb1dba2b7083b4f3e777d785a9

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by thomasplevy** [comment]
Hey @eri-trabiccolo I think we should scrap these merge codes all together... I'm looking at how to apply the merging to the description of either the meter or the password itself and it's starting to feel needlessly complicated...

If the default description assumes default values (strong and 8) can we just assume that users will *change them* when they update the options? Or should we not make this assumption and figure out how to merge in both places?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I read and re-read and I don't understand the question :D

**Comment by eri-trabiccolo** [comment]
@thomasplevy Ohhh I got it now.
Yeah yes let's do it. No merge codes, if you change the default value change the description accordingly. Yes agreed.
Also, since the initial default value actually depends on an "legacy option" I think we should just remove the references to the merge code values in the current default description.

Do you agree?

**Comment by thomasplevy** [comment]
@eri-trabiccolo Can you update the text and description in this PR to remove the reference to the merge codes and we'll remove the merging functionality from the core as a [separate issue](https://github.com/orgs/gocodebox/projects/12#card-62427571)

**Comment by eri-trabiccolo** [comment]
@thomasplevy updated
