### ISSUE TITLE
Unique field names handling needs to be improved(?)

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#103]
### Reproduction Steps

+ Edit a form and create a field, using the hame "whatever"
+ Turn it to a reusable block and save it
+ Create or edit another form and add the reusable block just created
+ turn the reusable block into a normal block
+ Alter the label, the description, whatever (but not the name)
+ save the form

### Expected Behavior

+ I'd expect to not be able to save the field, which is not a reusable field anymore, because it has a non unique name 

### Actual Behavior

+ I can save the form with the field that has a non unique name

### Error Messages / Logs

n/a

### System and Environment Information

https://github.com/gocodebox/lifterlms-blocks/commit/dafd798e416017fb1dba2b7083b4f3e777d785a9

###This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by thomasplevy** [comment]
This is nearly identical to #104 but not exactly. It's all interrelated in that our automatically generated values / validation isn't working right in these scenarios.
