### ISSUE TITLE
Error notices in the editor can be "unnoticed" if you've scrolled the editor

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#109]
### Reproduction Steps

+ edit form
+ scroll the editor a little bit
+ generate a field validation error, e.g.:
 create a field with name "ab"
 create another field and try to set its name to "ab"

### Expected Behavior

+ I'd expect to see the error notice informing me about the fact I cannot use the same name twice

### Actual Behavior

+ The last character of the name attribute gets stripped to fix the name duplication, an error notice is printed at the top of the editor but I can't see it unless I scroll back to the top

### Error Messages / Logs

```
n/a

```

### System and Environment Information

WordPress 5.8

### This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by thomasplevy** [comment]
I think this is a Gutenberg/WP 5.8 "regression" although it's "blessed" as an acceptable casualty so we may have to adjust our validation message strategy given the change, I've raised an issue about this and I'm not going to make any changes until we have an answer there: https://github.com/WordPress/gutenberg/issues/32593

**Comment by thomasplevy** [comment]
Hows this look at @eri-trabiccolo 
![Peek 2021-06-10 15-24](https://user-images.githubusercontent.com/1290739/121604793-09504b80-ca00-11eb-95ad-78019da04388.gif)

**Comment by eri-trabiccolo** [comment]
@thomasplevy that's the way

**Comment by thomasplevy** [comment]
The core issue should be resolve in GB at some point (see https://github.com/WordPress/gutenberg/pull/32488) and https://github.com/gocodebox/lifterlms-blocks/commit/2082ccc1573eb8fd577189d95c6f59b3f50132e5 fixes the inciting incident warranting this bug report, however we are still using notices in this way to handle the require blocks for each form type. I don't see a good way to convert them to inline warnings like this so I'm going to leave this open for the time being as a reference for the future

**Comment by eri-trabiccolo** [comment]
Mmm right, ai forgot about the required blocks...
Although the difference with that would be that it pops only on save... I wonder if there's a way to hook there and, in case, scroll the editor pane to the top...
