### ISSUE TITLE
block_categories filter is deprecated

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms-blocks#135]
### Reproduction Steps

1. Use the [development version of WordPress 5.8](https://github.com/WordPress/wordpress-develop/tree/5.8.0).
1. Enable WordPress debugging mode in `wp-config.php`.
    ```php
    define( 'WP_DEBUG', true );
    ```
1. Edit any WordPress post or a custom post type like a LifterLMS course.

### Expected Behavior

The WordPress navigation menu is displayed normally without errors or warnings.

### Actual Behavior

The WordPress navigation menu on the left side of the page contains errors.

### Error Messages / Logs

```
Deprecated: block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in C:\WordPress\src\wp-includes\functions.php on line 5458
```

### System and Environment Information

global $wp_version = "5.8-src"

I turned off all WordPress extensions except LifterLMS. When LifterLMS is deactivated, editing a post does not display errors in the WP navigation menu.

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment]
@pondermatic but 5.8 stable is out :D
Thomas fixed this for 5.8 stable and above:
https://github.com/gocodebox/lifterlms-blocks/blob/trunk/includes/class-llms-blocks.php#L172-L174

**Comment by pondermatic** [comment]
```php
var_dump(version_compare( '5.7', '5.8-alpha.1', '>='));
bool(false)

var_dump(version_compare( '5.8', '5.8-alpha.1', '>='));
bool(true)

var_dump(version_compare( '5.8-src', '5.8-alpha.1', '>='));
bool(false)
```

**Comment by eri-trabiccolo** [comment]
ah, I see what you mean, well not sure we should add another `version_compare` check for devs who use `5.8-src`.
They can turn off the the error displaying (and log it only).
But yeah, I guess we can turn that line:
`		$filter = version_compare( $wp_version, '5.8-src', '>=' ) ? 'block_categories_all' : 'block_categories';`
that should work, right?

**Comment by pondermatic** [comment]
You are correct, this does seem to work.
```php
$filter = version_compare( $wp_version, '5.8-src', '>=' ) ? 'block_categories_all' : 'block_categories';
```
I am going to do some more tests with various strings to make sure.

Should I write a unit test for this?

BTW, I am one of those devs who uses the development version of WordPress and I need WP_DEBUG = true.

**Comment by pondermatic** [comment]
Strings are handled by [version_compare](https://www.php.net/manual/en/function.version-compare.php) this way:
`any string not found in this list < dev < alpha = a < beta = b < RC = rc < # < pl = p`.

So 'src' is less than 'alpha'.

**Comment by eri-trabiccolo** [comment]
> You are correct, this does seem to work.
> 
> ```
> $filter = version_compare( $wp_version, '5.8-src', '>=' ) ? 'block_categories_all' : 'block_categories';
> ```
> 
> I am going to do some more tests with various strings to make sure.
> 
> Should I write a unit test for this?

Thomas loves them :P 

> BTW, I am one of those devs who uses the development version of WordPress and I need WP_DEBUG = true.

Yeah I figured it :P 
Nothing against it, I'm just with the git version and I update it sometimes :D ~Just updated it and found the block editor "broken" because of our blocks plugin!!! :@~**[edit: I was running an old llms-blocks version]**
BTW yeah I always have the `WP_DEBUG` set to `true`, I just never display the errors, I log them. Displaying errors/warnings break the html too easily, and most of the times warnings come from 3rd party plugins/themes. So I go with
```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
define( 'SCRIPT_DEBUG', true );
```

and always check the debug.log in wp-content.

**Comment by pondermatic** [comment]
I'll admit that the development version of WordPress has been a pain occasionally.

**Comment by thomasplevy** [comment]
I'm okay with just updating it to `-src` and moving on. We don't need to lose our minds about this.

**Comment by pondermatic** [comment]
Ooops, too late. Unit test written. Mind lost.
