### ISSUE TITLE
Most blocks should only be registered for specific post types

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-blocks#20]
Currently looks like it's not strictly possible to make a block available only to a specific post type. See core issue threads:
https://github.com/WordPress/gutenberg/issues/10951
https://github.com/WordPress/gutenberg/issues/9855
https://github.com/WordPress/gutenberg/issues/2685

**Comment by manake** [comment]
Is there any workaround for now?

`add_filter( 'allowed_block_types', function( $allowed_block_types, $post ) {` doesn't allow excluding blocks and I see no way to list all available blocks to cheat it...

**Comment by thomasplevy** [comment]
@manake I've spent a pretty significant amount of time trying to review available filters and hooks to see if I can work around this. I haven't found a workaround thus this issue... If you come up with something I'm all ears but I haven't found anything...

**Comment by thomasplevy** [comment]
@manake if you're still looking to solve this I did so via the following strategy (check the commit for specifics)

1) Output a global window object with low priority (eg 1) via `admin_head` that allows you to access the current post type via Javascript, eg:
```php
add_action( 'admin_head', function() {
   global $post;
   ?>
   <script>window.my_post_type = '<?php echo $post->post_type; ?>';</script>
   ?>
}, 1 );
```
2) Access the post type variable in js and conditionally register your block only for the post type you want it avialable to
```js
if ( 'my_post_type' === window.my_post_type ) {
   registerBlockType( 'my-block', { ... } );
}
```

It's hacky but it's working for us
