### ISSUE TITLE
The Mark Complete button on the back-end does not match how it looks on the front-end.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms-blocks#201]
### Reproduction Steps
How the _Mark Complete_ button looks on the front-end does not match the back-end, [as you can see in this screenshot](https://share.getcloudapp.com/P8uXypnX).

### Expected Behavior
How the _Mark Complete_ button looks on the front-end should match the back-end.

### Actual Behavior
How the _Mark Complete_ button looks on the front-end does not match the back-end.

### This issue has been recreated:

+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Related User Information
HS-218701.

**Comment by eri-trabiccolo** [comment]
@dominiquemariano 
did you try with other themes as well?

**Comment by dominiquemariano** [comment]
> @dominiquemariano did you try with other themes as well?

This is how it looks like on Twenty Twenty Three: https://share.getcloudapp.com/8LuYryYg
