### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-blocks#3]
- [ ] Add i18n compiler build step
- [ ] load text domain via `setLocaleData()`

**Comment by thomasplevy** [comment]
Reported as issue https://github.com/gocodebox/lifterlms/issues/1110#issuecomment-615409484 & https://github.com/gocodebox/lifterlms/issues/1110#issuecomment-615409076

**Comment by alaa-alshamy** [comment]
@thomasplevy  Is there any updates here ?

the js strings of the Lifterlms blocks is not translatable like "Course Information" block

and that's only in the block editor, so when open the course in the front end every thing is alright

**Comment by thomasplevy** [comment]
@alaa-alshamy 

No update yet, sorry.
