### ISSUE TITLE
Fall back on `wp.editor` if  `wp.blockEditor` doesn't exist?!

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#34]
As far as I can see the `wp.blockEditor` has been introduced in 5.2 right?
https://make.wordpress.org/core/2019/04/09/the-block-editor-javascript-module-in-5-2/

This means that with:
https://github.com/gocodebox/lifterlms-blocks/commit/dfc51fd388ea2d6e5154a50ced4bba5fc14467d8

if we don't introduce a fall back on `wp.editor`, we have to push the WP supported min version.

**Comment by thomasplevy** [comment]
I was just fixing what was an overwhelming number of deprecation warnings thrown by the core... I didn't even consider that the update wouldn't be backwards compatible...

I'll rework this, thanks
