### ISSUE TITLE
Course Instructors changes not persisting since WP 5.3

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#38]
### 1. Reproduction Steps

+ Edit a course with WP 5.3
+ Click on the LifterLMS rocket button to open the Instructors settings
+ Add a new instructor to the course or make any change to the existing one (e.g. visibility, label)
+ Update the course
+ either refresh the page or toggle off/on the instructors settings (e.g. by clicking on the rocket button)

### 2. Expected Behavior

I would expect the changes I made to be applied.

### 3. Actual Behavior

Changes do not persist on post update.

### 4. Error Messages / Logs

n/a

### 5. System Report
WP 5.3
LifterLMS 3.37.2
theme: TwentyTwenty
(no other plugins installed)

### 6. Browser, Device, and Operating System
Chrome/Firefox 

### ADDITIONAL CONSIDERATIONS

reported on hs

I cannot reproduce the issue with WP 5.2.4

**Comment by eri-trabiccolo** [comment]
Interesting:
1) Sometimes, like 1 out of 15 it works
2) the instructor removal always works

**Comment by eri-trabiccolo** [comment]
Another "test" that maybe can help you @thomasplevy understanding what's going on.
Do this:

0) On a course with the default instructor
1) Add an instructor
2) Update
3) refresh
The new instructor is not saved

go back to step 0)
1) Add an instructor
2) Sort the instructors list so that the new instructor now sits "above" (before) the default instructor: basically be sure that the order is not the "original" one.
3) update
4) refresh
The new instructor and the "new" order is saved.

go back to step 0)
1) Add an instructor
2) drag multiple times the instructors BUT make sure that the final order matches the "original" one.
3) update
4) refresh
The new instructor and the "new" order is NOT saved.

**Comment by thomasplevy** [comment]
I think our issue is related to this: https://make.wordpress.org/core/2019/10/03/wp-5-3-supports-object-and-array-meta-types-in-the-rest-api/

**Comment by eri-trabiccolo** [comment]
Mmm, but why reordering the instructors then works?

**Comment by thomasplevy** [comment]
@eri-trabiccolo reordering doesn't seem to work on my end...

**Comment by eri-trabiccolo** [comment]
@thomasplevy weird...

**Comment by eri-trabiccolo** [comment]
@thomasplevy this issue has been closed because you merged #39 but the fix has not been included in the latest lifterlms release... That can be ok, but I have an user waiting for this to be fixed.
I think it might be my fault because I only wrote _reported on hs_ in my first message here (and now edited it adding the ticket id), on the other hand I added a not on hs referring to this issue.

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm working on ensuring that the changes in blocks work with the latest stuff in the core and will release an update later today (to the core) that includes the latest version of blocks with this bug fix.

I was aware of the HS issue but it slipped my mind and I neglected to build and release the latest version of blocks as a result.

I hope to have this out today, possibly not until tomorrow though.
