### ISSUE TITLE
Block editor broken on CPT that do not support custom fields

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#40]
### 1. Reproduction Steps

+ Create a cpt that supports the block editor `'show_in_rest' => true` BUT that does not support custom fields, so in the `'supports'` array make sure there's no `'custom-fields'`
+ edit the cpt with the block editor

### 2. Expected Behavior

+ expect to be able to edit the cpt

### 3. Actual Behavior

+ cannot edit the cpt, got block editor typical error
![Schermata 2019-12-09 alle 22 26 41](https://user-images.githubusercontent.com/7689242/70474503-0440d200-1ad3-11ea-86ce-2a543a44ce4e.png)

### 4. Error Messages / Logs

Here's the error copied from the block editor:

> Error: An error occurred while running 'mapSelect': Cannot read property '_llms_form_location' of undefined
> The error may be correlated with this previous error:
> TypeError: Cannot read property '_llms_form_location' of undefined
>     at eval (webpack-internal:///342:191:43)
>     at Object.mapSelect [as current] (http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:2808:16)
>     at onStoreChange (http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:2712:46)
>     at http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:2739:9
>     at http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:1980:14
>     at Array.forEach (<anonymous>)
>     at globalListener (http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:1979:15)
>     at http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:1592:9
>     at dispatch (http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:676:7)
>     at http://one.wordpress.test/wp-includes/js/dist/redux-routine.js?ver=3.6.2:910:18
> 
> Original stack trace:
>     at useSelect (http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:2692:13)
>     at http://one.wordpress.test/wp-includes/js/dist/data.js?ver=4.9.2:2811:24
>     at renderWithHooks (http://one.wordpress.test/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:15246:18)
>     at updateFunctionComponent (http://one.wordpress.test/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:17063:20)
>     at beginWork$1 (http://one.wordpress.test/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:18636:16)
>     at HTMLUnknownElement.callCallback (http://one.wordpress.test/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:341:14)
>     at Object.invokeGuardedCallbackDev (http://one.wordpress.test/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:391:16)
>     at invokeGuardedCallback (http://one.wordpress.test/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:448:31)
>     at beginWork$$1 (http://one.wordpress.test/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:23355:7)
>     at performUnitOfWork (http://one.wordpress.test/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:22349:12)
> 

### 5. System Report

LifterLMS 3.37.4
WordPress 5.4

### 6. Browser, Device, and Operating System

n/a

### Considerations

The issue seems to be generated here:
https://github.com/gocodebox/lifterlms-blocks/blob/728f8cd94a139496b3cb6a2856eb0f72c36f7e02/src/sidebar/form-document-settings/index.js#L151

I roughly printed `getEditedPostAttribute( 'meta' )` before that line and it's `undefined`, so I think we should make sure that `getEditedPostAttribute( 'meta' )` is defined before trying to access its properties.

There are other references to the post meta and `_llms_form_*` throughout the code that I haven't really tested yet at the moment.

This issue has been reported on wp.org forum https://wordpress.org/support/topic/last-update-breaks-gutenberg/

and on hs # 107034

**Comment by thomasplevy** [comment]
Darn... I knew this wasn't tested enough to fully release. Sorry about that...

**Comment by thomasplevy** [comment]
The post type check

https://github.com/gocodebox/lifterlms-blocks/blob/728f8cd94a139496b3cb6a2856eb0f72c36f7e02/src/sidebar/form-document-settings/index.js#L74

Should be moved to within the applyWithDispatch call at

https://github.com/gocodebox/lifterlms-blocks/blob/728f8cd94a139496b3cb6a2856eb0f72c36f7e02/src/sidebar/form-document-settings/index.js#L161

I think... I'll setup a test case after I get done with what I'm working on right this moment and see if I can't deploy at hotfix before end of day..

**Comment by eri-trabiccolo** [comment]
I think you're right, it was late, I just noticed those tickets, and wanted to file an issue but not without giving you at least a rough analysis on why and where the issue occurred :)

**Comment by thomasplevy** [comment]
Reproducible with this cpt code:

```php
// Register Custom CPT
function custom_post_type() {

	$labels = array(
		'name'                  => _x( 'CPTs', 'CPT General Name', 'text_domain' ),
		'singular_name'         => _x( 'CPT', 'CPT Singular Name', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'CPT', 'text_domain' ),
		'description'           => __( 'CPT Description', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'show_in_rest' => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'post_type', $args );

}
add_action( 'init', 'custom_post_type', 10 );
```

Important parts are that the CPT supports rest and does NOT support custom fields (as @eri-trabiccolo noted above)
