### ISSUE TITLE
Block: Course Information Causes No HTML Returned when contents are set to false

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms-blocks#43]
### 1. Reproduction Steps

On a course select the Course Information block. 
Turn off all of the information options.

<img src="https://i.imgur.com/0M1ReQI.png">

### 2. Expected Behavior

The block will display as empty. 

### 3. Actual Behavior

The block on the visibility editor appears as empty but still displays this code in the code editor:

`<!-- wp:llms/course-information {"title":"Information","show_cats":false,"show_difficulty":false,"show_length":false,"show_tags":false,"show_tracks":false} /—>`

and displays a "no HTML returned" on the front end. 

<img src="https://i.imgur.com/bS80G1B.png">

**Comment by nrherron92** [comment]
I agree, that makes more sense to do. My guess is this person turned off all the information, saw that the title disappeared and then perhaps thought the block had been removed so then didn't actually think to remove it or that it needed to then be deleted.

**Comment by thomasplevy** [comment]
The "no html returned" serves as a kind of error message / indicator that the block isn't functioning. Perhaps the logic should be adjusted to include some sort of error message and be displayed to admins only. In any event the interim solution is to just delete the block!

**Comment by nrherron92** [comment]
Yeah that could work. Though, you would have to know to go into the code editor and find that line of code to remove it manually. The block disappears in the visual editor once it's had all of the settings turned off and you can't click it again. Yeah, if you just delete the block the issue goes away all and everything works as expected.

**Comment by thomasplevy** [comment]
@nrherron92 okay I didn't realize the block isn't clickable with everything disabled.

That changes the severity. We'll work on this shortly.

**Comment by eri-trabiccolo** [comment]
yes @thomasplevy but still you can "access" it if you click on the block navigation icon, although it might be more complex.
![Schermata 2020-02-26 alle 17 29 31](https://user-images.githubusercontent.com/7689242/75365541-a2b42680-58bd-11ea-8eac-ae0e52814e2d.png)

**Comment by thomasplevy** [comment]
@eri-trabiccolo sure, of course, but if it's "disappeared" on the backend and isn't clickable in the editor itself it's actually a lot more obtuse and difficult to use than I had first thought. We'll have to fix this regardless now -- and I think this may affect some other blocks as well, I'll have to take a closer look.
