### ISSUE TITLE
Block visibility settings don't work with VDOCipher plugin

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-blocks#53]
### Reproduction Steps

+ Install  Vdo Cipher
+ Add an AB Block to a course.
+ Set the restriction to anything but the default and save.
+ Refresh the page.

### Expected Behavior

+ The restriction settings would be saved and applied to the block on the front end.

### Actual Behavior

+ The settings get reset to the default

HS-117906 (VdoCipher -- he hasn't actually given us access to his site but I confirmed locally)

**Comment by thomasplevy** [comment]
@nrherron92 

This issue results from a typo that is resolved in #51 

When this issue is merged in the "visibility" settings will no longer be displayed at all (because they are not supported by this block).

The VDOCipher Block is a "dynamic" block which means it's rendered with PHP and therefore we are unable to register custom visibility settings to the block of this kind. There's a handful of core blocks that we don't support (Archives, is one of them). Some of our core blocks are dynamic blocks but we have our own custom support for their visibility.

In any event, we *cannot* make this work however I believe it can be worked around by wrapping the VDOCipther block in a "group" block and setting the visibility on the group block. Could you provide this solution and information to the customer?

There's no need to wait for the update since even after the update this block WILL NOT WORK. THe update fixes the bug that allows the visibility settings to be seen for this block (and other dynamic blocks too).

**Comment by nrherron92** [comment]
@thomasplevy I updated the user! I'll close this out!
