### ISSUE TITLE
block migration broken for courses since 1.9.0

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-blocks#61]
### 1. Reproduction Steps

+ Create a new course using the course importer, import the sample course provided with the LifterLMS core
+ Navigate to the block editor for the imported course

### 2. Expected Behavior

+ The course progress block should be visible without errors

### 3. Actual Behavior

+ The course progress block shows an error from invalid HTML content

### 4. Error Messages / Logs

The block will display the error: "This block contains unexpected or invalid content"

### 5. Additional Information

This is resulting from changing the block from a static JS block to a dynamic php block.

The previous content of the block would be:

```html
<!-- wp:llms/course-progress -->
<div class="wp-block-llms-course-progress">[lifterlms_course_progress]</div>
<!-- /wp:llms/course-progress -->
```

Or (briefly but never in production):
```html
<!-- wp:llms/course-progress -->
<div class="wp-block-llms-course-progress">[lifterlms_course_progress check_enrollment=1]</div>
<!-- /wp:llms/course-progress -->
```

The expected output of the block is now:
```html
<!-- wp:llms/course-progress / -->
```

The template in the post migrator class should be updated to:

1. Remove the static version from 1.8.0 that was never actually released in production.
2. Update the "merge deprecated versions" to wrap the entire old version
3. Add the default to be the proper version of the block as expected by the new dynamic block

**Comment by thomasplevy** [comment]
Placing this as high severity because it's now blocking the core release 3.38.0 which contains many many bug fixes.

**Comment by eri-trabiccolo** [comment]
ohhh stupid me,
this
```php
<!-- wp:llms/course-progress -->
<div class="wp-block-llms-course-progress">[lifterlms_course_progress check_enrollment=1]</div>
			<?php if ( $merge_deprecated_versions ) : ?>
<div class="wp-block-llms-course-progress">[lifterlms_course_progress]</div>
			<?php endif; ?>
<!-- /wp:llms/course-progress -->
```
in the migrator should be:

```php
<!-- wp:llms/course-progress / -->
			<?php if ( $merge_deprecated_versions ) : ?>
<!-- wp:llms/course-progress -->
<div class="wp-block-llms-course-progress">[lifterlms_course_progress check_enrollment=1]</div>
<div class="wp-block-llms-course-progress">[lifterlms_course_progress]</div>
<!-- /wp:llms/course-progress -->
			<?php endif; ?>
```

right?
This is the issue, right?
