### ISSUE TITLE
Blocks not compatibile with WP 5.2.6 (at least) - making impossible to create a new course

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#62]
### Reproduction Steps

+ Install WP 5.2.6
+ Try to create a new Course
+ Import our sample Course.

### Expected Behavior

+ I would expect everything working

### Actual Behavior

+ I cannot create a new Course: blank page when clicking on Add Course
+ I get a bunch of blocks errors when editing the imported sample course.

### Error Messages / Logs

console errors with **chrome** creating a new course:
![Schermata 2020-05-15 alle 15 03 32](https://user-images.githubusercontent.com/7689242/82053264-5c50b580-96bd-11ea-8236-725c78b77cfc.png)

console errors with **firefox** creating a new course:
![Schermata 2020-05-15 alle 15 05 18](https://user-images.githubusercontent.com/7689242/82053361-8609dc80-96bd-11ea-9df9-fea88db52443.png)

### Screenshot
(editing the sample course)
![Schermata 2020-05-15 alle 14 58 25](https://user-images.githubusercontent.com/7689242/82052920-bb61fa80-96bc-11ea-9862-76764a45f905.png)

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: http://old.wordpress.test
Site Url: http://old.wordpress.test
Login Url: http://old.wordpress.test/wp-login.php
Version: 5.2.6
Debug Mode: Yes
Debug Log: Yes
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.38.1
Db Version: 3.38.1
Course Catalog: Course Catalog (#5) [http://old.wordpress.test/courses/]
Membership Catalog: Membership Catalog (#6) [http://old.wordpress.test/memberships/]
Student Dashboard: Dashboard (#8) [http://old.wordpress.test/dashboard/]
Checkout Page: Purchase (#7) [http://old.wordpress.test/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: rock@local.it
Email From Name: Old
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 1 GB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.2.31-1+ubuntu18.04.1+deb.sury.org+1
Software: nginx/1.17.10
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Nineteen
Version: 1.4
Themeuri: https://wordpress.org/themes/twentynineteen/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 3.38.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
HS-121389

The use updated WP to the latest version and fixed it.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
can you take a look at this? Should we bump our requirements?

**Comment by thomasplevy** [comment]
@eri-trabiccolo I haven't had the mental or physical capacity to review this. Honestly have affected users upgrade WordPress, we'll review when we have some time and ensure it remains backwards compatible. I don't want to bump the version requirements we'll leave this as a bug and fix it when we have some time. If I'm wrong and a GREAT NUMBER (more than is being noted in this thread) are being affected we can change priority.

**Comment by eri-trabiccolo** [comment]
[still low priority I know - that's why I don't ping you, - I just wanted to update you on my findings.]

Soooo the issue is here:
https://github.com/gocodebox/lifterlms-blocks/blob/1.9.1/assets/js/llms-blocks.asset.php#L1
specifically `'wp-server-side-render'`, which doesn't exist for that "old" WordPress version: the `ServerSideRender` in 5.2.6 was part of `wp.components` (I think the move happened in 5.3 but I cannot find any reference at the moment).

This means that our main block js file is not loaded at all, as `wp-server-side-render` is a dep for it:
https://github.com/gocodebox/lifterlms-blocks/blob/1.9.1/includes/class-llms-blocks-assets.php#L52

Of course when "removing" that dep the block editor loads but all the blocks that rely on that dep just break.

But, as we can imagine, "removing" that dep + replacing
`import ServerSideRender from '@wordpress/server-side-render';`
with
`import { ServerSideRender } from '@wordpress/components';`

fixes the issue.

Is there a known "best way" to handle this?

**Comment by ajitbohra** [comment]
ServerSideRender was extracted to a separate package and is backward-compatible https://github.com/WordPress/gutenberg/blob/a9969461313118d76af95f696d78d26a5ea2e29c/packages/server-side-render/src/index.js#L43 `wp.components.ServerSideRender` not yet depreacted.

`wp.components.ServerSideRender` can still be used so it works on older as well as new version of WordPress.

Another approach can be shipping/Enqueuing `ServerSideRender` package script and conditional loading on WordPress < 5.3

**Comment by thomasplevy** [comment]
@ajitbohra 

Thanks for ringing in here to help out.

> `wp.components.ServerSideRender` can still be used so it works on older as well as new version of WordPress.

If we do this though, we get hit with deprecation warnings (which is why we made changes to use `ServerSideRender` directly in this commit: https://github.com/gocodebox/lifterlms-blocks/commit/f22a9f8f39852b02dc469f8f30007e001ec653f3

It seems to me that maybe I misunderstood what "backwards compatible" meant in this switch.

It is backwards compatible but the script loading asset builder (handled by the @wordpress/scripts) doesn't handle backwards compatibility of the named packages for us. Am I following/understanding correctly?

**Comment by thomasplevy** [comment]
I'm closing this. Never heard back and now that i understand what to do it's a bit late. We're dropping support for 5.2 next week anyway via https://github.com/gocodebox/lifterlms/pull/1551
