### ISSUE TITLE
Editor: Some (server side rendered) blocks break when the plugin Ultimate Addons for Gutenberg is active

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#85]
### Reproduction Steps

+ Install https://wordpress.org/plugins/ultimate-addons-for-gutenberg/
+ edit/create a Course (or a Membership or a Lesson)

### Expected Behavior

+ Everything should look normal

### Actual Behavior

+ Some (server side rendered) blocks break

### Error Messages / Logs
![image](https://user-images.githubusercontent.com/7689242/112497685-21f88000-8d86-11eb-8ded-4d0427359b43.png)

### System and Environment Information

<details>
<summary>System Report</summary>

```
LifterLMS 4.20.0
Gutenberg Blocks – Ultimate Addons for Gutenberg 1.22.1
WordPress 5.7
```

</details>

### This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
Reported by Adrian Tobey on our Slack #developers channel.
https://lifterlms.slack.com/archives/CCESQHE82/p1616595631053700

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'll look at this while I'm working on editor stuff today, if there's not a quick fix this will wait until after 5.x

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm going to mark this as invalid. It looks to me as if this plugin is not properly registering their custom block attributes. This means that when the block editor runs REST request to render server-side rendered blocks a 400 error is generated as a result of invalid block attributes being passed to the controller.

Request:
`https://llms.test/wp-json/wp/v2/block-renderer/llms/instructors?context=edit&attributes%5Bpost_id%5D=0&attributes%5BUAGHideDesktop%5D=false&attributes%5BUAGHideMob%5D=false&attributes%5BUAGHideTab%5D=false&attributes%5BUAGLoggedIn%5D=false&attributes%5BUAGLoggedOut%5D=false&attributes%5Bllms_visibility%5D=all&attributes%5Bllms_visibility_in%5D=&attributes%5Bllms_visibility_posts%5D=%5B%5D&post_id=191138&_locale=user`


Response: 
```json
{
  "code": "rest_invalid_param",
  "message": "Invalid parameter(s): attributes",
  "data": {
    "status": 400,
    "params": {
      "attributes": "UAGHideDesktop is not a valid property of Object."
    },
    "details": {
      "attributes": {
        "code": "rest_additional_properties_forbidden",
        "message": "UAGHideDesktop is not a valid property of Object.",
        "data": null
      }
    }
  }
}
```

The solution here is for the plugin to register it's block properties using `register_rest_field()`.

It's possible for us to fix this within our plugin but this isn't really a bug in LifterLMS at all, we're just seeing it on our dynamic blocks. You'll see the same errors on a WordPress page with WP core dynamic blocks:

1. Make a new page
2. Add an "Archives" block to the page
3. See the same 400 error from the REST request in the dev tools network tab
